# Generated by Django 4.1.5 on 2023-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                ("itemId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
