# Generated by Django 4.1.5 on 2023-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeitem",
            name="image",
            field=models.ImageField(upload_to="images/store_icons"),
        ),
    ]
