# Generated by Django 4.1.7 on 2023-03-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('buildingName', models.CharField(max_length=100)),
                ('qrCode', models.ImageField(upload_to='')),
            ],
        ),
    ]
