# Generated by Django 4.1.5 on 2023-03-20 22:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.0"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.0"), max_digits=9
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="radius",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=5
            ),
        ),
    ]
