# Generated by Django 4.1.5 on 2023-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_location_latitude_location_longitude_location_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="qrCode",
            field=models.CharField(max_length=50),
        ),
    ]
