# Generated by Django 4.1.5 on 2023-03-08 15:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerGroup",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
            ],
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("memberSince", models.DateTimeField()),
                (
                    "bin",
                    models.ManyToManyField(related_name="players", to="event.trash"),
                ),
                ("storeItems", models.ManyToManyField(to="store.storeitem")),
            ],
        ),
    ]
