# Generated by Django 4.1.5 on 2023-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_remove_trash_player"),
        ("logins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="bin",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="players", to="event.trash"
            ),
        ),
    ]
