# Generated by Django 4.1.5 on 2023-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logins", "0003_alter_player_bin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="bin",
        ),
    ]
