# Generated by Django 4.1.5 on 2023-03-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logins", "0004_remove_player_bin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="memberSince",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
