# Generated by Django 4.1.5 on 2023-03-22 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_trash_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logins", "0005_alter_player_membersince"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="attempted_events",
            field=models.ManyToManyField(
                related_name="players_attempted", to="event.event"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="player",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
