# Generated by Django 4.1.5 on 2023-03-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboard",
            options={"ordering": ["-total_value"]},
        ),
    ]
