"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY SETTINGS
# -----------------
SECRET_KEY = 'django-insecure-cscs7blctgkkef410$-n=dykp7gznw)8-x^7f2$y@0_(5^$0xu'
DEBUG = True
ALLOWED_HOSTS = ['10.173.107.49', '127.0.0.1', '192.168.1.161','192.168.0.93', '10.173.107.246', 'trash2treasure.info', 'ecm2434-sustainabilitygame-2023-cloud-zvtoiun5xa-ew.a.run.app']
CSRF_TRUSTED_ORIGINS = ['https://trash2treasure.info','https://ecm2434-sustainabilitygame-2023-cloud-zvtoiun5xa-ew.a.run.app']

# APPLICATIONS
# ------------
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'event.apps.EventConfig',
    'logins.apps.LoginsConfig',
    'bin.apps.BinConfig',
    'settings.apps.SettingsConfig',
    'location.apps.LocationConfig',
    'resources.apps.ResourcesConfig',
    'store.apps.StoreConfig',
    'main.apps.MainConfig',
    'leaderboard.apps.LeaderboardConfig',
]

# MIDDLEWARE
# ----------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URLS & TEMPLATES
# ----------------
ROOT_URLCONF = 'website.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.csrf',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'website.wsgi.application'

# DATABASE
# --------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PASSWORD VALIDATION
# -------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# INTERNATIONALIZATION
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# STATIC FILES & MEDIA
# --------------------
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
LOGIN_URL = '/login/'

# DEFAULT AUTO FIELD
# ------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'